module.exports = {
  SERVER_ERROR: "SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",

  NOT_FOUND: "NOT_FOUND",

  INVALID_BODY: "INVALID_BODY",
  CARD_NOT_VALIDATED: "CARD_NOT_VALIDATED",

  INVALID_PRICE: "INVALID_PRICE",

  ERROR_PARSING_JSON_RESPONSE: "ERROR_PARSING_JSON_RESPONSE",
  ERROR_EXTRACTING_CONTENT: "ERROR_EXTRACTING_CONTENT",
  CLIENT_NOT_VALID: "CLIENT_NOT_VALID",
  NO_FILES_PROVIDED: "NO_FILES_PROVIDED",

  MISSING_PARAMETERS: "MISSING_PARAMETERS",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
};
